#!/usr/bin/env python3
"""Generate attack catalog tables and the full attacks overview from attacks.yaml.

Single source of truth: taxonomy/attacks.yaml
Targets (rewritten in-place between generated markers):
  - taxonomy/families/<family>/README.md              (combined family table)
  - taxonomy/families/<family>/<category>.md          (per-leaf tables)
  - taxonomy/attacks-overview.md                      (complete cross-family catalog)

Generated regions are delimited by HTML comments:
  <!-- BEGIN GENERATED: attack-catalog -->   (family READMEs and category docs)
  <!-- BEGIN GENERATED: attacks-overview --> (attacks-overview.md)

Usage:
  python scripts/generate_tables.py          # regenerate tables in place
  python scripts/generate_tables.py --check  # exit 1 if any file would change (CI)

The --check mode is used in CI to guarantee that attacks.yaml and the
rendered tables stay in sync. If a contributor edits attacks.yaml without
regenerating the tables, CI fails with a diff.

Leaf paths in attacks.yaml must match canonical IDs from taxonomy.yaml in
the form {family_id}.{category_id}.{leaf_id}.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Iterable

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "error: PyYAML is required. Install with: pip install pyyaml\n"
    )
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parent.parent
ATTACKS_FILE = REPO_ROOT / "taxonomy" / "attacks.yaml"
TAXONOMY_FILE = REPO_ROOT / "taxonomy" / "taxonomy.yaml"
FAMILIES_DIR = REPO_ROOT / "taxonomy" / "families"
OVERVIEW_FILE = REPO_ROOT / "taxonomy" / "attacks-overview.md"

CATALOG_LABEL = "attack-catalog"
OVERVIEW_LABEL = "attacks-overview"
GENERATED_NOTE = (
    "<!-- This section is generated by scripts/generate_tables.py. "
    "Do not edit by hand. Update taxonomy/attacks.yaml instead. -->"
)

def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_taxonomy_index(taxonomy: dict) -> dict[str, dict]:
    """Index taxonomy.yaml by canonical leaf path -> metadata."""
    index: dict[str, dict] = {}
    for family in taxonomy.get("families", []):
        fid = family["id"]
        fname = family["name"]
        for category in family.get("categories", []):
            cid = category["id"]
            cname = category["name"]
            for leaf in category.get("leaves", []):
                lid = leaf["id"]
                path = f"{fid}.{cid}.{lid}"
                index[path] = {
                    "family_id": fid,
                    "family_name": fname,
                    "category_id": cid,
                    "category_name": cname,
                    "leaf_id": lid,
                    "leaf_name": leaf["name"],
                    "leaf_prevalence": leaf.get("prevalence_pct"),
                    "category_prevalence": category.get("prevalence_pct"),
                    "family_prevalence": family.get("prevalence_pct"),
                }
    return index


def group_attacks(attacks: list[dict], index: dict[str, dict]) -> dict:
    """Group attacks into family -> category -> leaf -> [attack, ...]."""
    grouped: dict = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    unknown: list[str] = []
    for attack in attacks:
        leaf_path = attack.get("leaf", "")
        meta = index.get(leaf_path)
        if meta is None:
            unknown.append(f"{attack.get('name', '?')}: {leaf_path}")
            continue
        grouped[meta["family_id"]][meta["category_id"]][meta["leaf_id"]].append(attack)
    if unknown:
        sys.stderr.write(
            "warning: attacks with unresolved leaf paths (skipped):\n  - "
            + "\n  - ".join(unknown)
            + "\n"
        )
    return grouped


def _sort_attacks(attacks: list[dict]) -> list[dict]:
    return sorted(attacks, key=lambda a: a.get("name", "").lower())


def _md_link(label: str, url: str | None) -> str:
    if not url:
        return "—"
    return f"[{label}]({url})"


def _escape_cell(value: str) -> str:
    """Escape markdown table cell contents: pipes and newlines."""
    if value is None:
        return ""
    return str(value).replace("|", "\\|").replace("\r\n", " ").replace("\n", " ").strip()


def render_attack_row(attack: dict) -> str:
    name = _escape_cell(attack.get("name", ""))
    paper = _md_link("Link", attack.get("paper_url"))
    repo = _md_link("Repo", attack.get("repo_url"))
    venue = _escape_cell(attack.get("venue", ""))
    year = _escape_cell(attack.get("year", ""))
    return f"| {name} | {paper} | {repo} | {venue} | {year} |"


def render_models_details(attacks: list[dict]) -> str:
    """Collapsible list of models tested, one bullet per attack."""
    lines = ["<details>", "<summary>Models tested (click to expand)</summary>", ""]
    for attack in _sort_attacks(attacks):
        models = attack.get("models") or []
        # Flatten: models may be a list of strings (sometimes multi-model entries)
        flat = [str(m).strip() for m in models if str(m).strip()]
        if not flat:
            continue
        name = _escape_cell(attack.get("name", ""))
        lines.append(f"- **{name}**: " + " ".join(flat).replace("\n", " "))
    lines.append("")
    lines.append("</details>")
    return "\n".join(lines)


def render_category_catalog(
    category_meta: dict,
    leaves_by_id: dict[str, list[dict]],
    taxonomy_index: dict[str, dict],
) -> str:
    """Per-leaf sections for a category doc."""
    total = sum(len(a) for a in leaves_by_id.values())
    out: list[str] = []
    out.append("## Attack Catalog")
    out.append("")
    out.append(f"*{total} documented attacks across {len(leaves_by_id)} leaf nodes.*")
    out.append("")
    for leaf_id, attacks in sorted(leaves_by_id.items()):
        leaf_path = f"{category_meta['family_id']}.{category_meta['category_id']}.{leaf_id}"
        leaf_meta = taxonomy_index.get(leaf_path, {})
        leaf_name = leaf_meta.get("leaf_name", leaf_id)
        out.append(f"### {leaf_name}")
        out.append("")
        out.append("| Attack | Paper | Repository | Venue | Year |")
        out.append("|--------|-------|------------|-------|------|")
        for attack in _sort_attacks(attacks):
            out.append(render_attack_row(attack))
        out.append("")
        out.append(render_models_details(attacks))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_family_catalog(
    family_id: str,
    family_name: str,
    categories: dict[str, dict[str, list[dict]]],
    taxonomy_index: dict[str, dict],
) -> str:
    """Combined family-level table grouped by category, with leaf column."""
    total = sum(len(a) for cat in categories.values() for a in cat.values())
    out: list[str] = []
    out.append("## Attack Catalog")
    out.append("")
    out.append(
        f"*{total} documented attacks across {family_name}. "
        "Grouped by category; see category docs for inclusion cues, "
        "canonical examples, and models tested.*"
    )
    out.append("")
    for category_id, leaves_by_id in sorted(categories.items()):
        # Look up category display name via any leaf under it
        sample_leaf = next(iter(leaves_by_id.keys()), None)
        category_name = category_id
        if sample_leaf:
            sample_meta = taxonomy_index.get(
                f"{family_id}.{category_id}.{sample_leaf}", {}
            )
            category_name = sample_meta.get("category_name", category_id)
        cat_count = sum(len(a) for a in leaves_by_id.values())
        out.append(
            f"### {category_name} "
            f"([details]({category_id}.md)) — {cat_count} attacks"
        )
        out.append("")
        out.append("| Attack | Leaf | Paper | Repository | Venue | Year |")
        out.append("|--------|------|-------|------------|-------|------|")
        # Flatten and sort by leaf, then name
        rows: list[tuple[str, str]] = []
        for leaf_id, attacks in leaves_by_id.items():
            leaf_meta = taxonomy_index.get(
                f"{family_id}.{category_id}.{leaf_id}", {}
            )
            leaf_name = leaf_meta.get("leaf_name", leaf_id)
            for attack in attacks:
                rows.append((leaf_name, _family_row(attack, leaf_name)))
        for _, row in sorted(rows, key=lambda x: (x[0].lower(), x[1].lower())):
            out.append(row)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _family_row(attack: dict, leaf_name: str) -> str:
    name = _escape_cell(attack.get("name", ""))
    leaf = _escape_cell(leaf_name)
    paper = _md_link("Link", attack.get("paper_url"))
    repo = _md_link("Repo", attack.get("repo_url"))
    venue = _escape_cell(attack.get("venue", ""))
    year = _escape_cell(attack.get("year", ""))
    return f"| {name} | {leaf} | {paper} | {repo} | {venue} | {year} |"


def splice_generated(content: str, generated_body: str, label: str) -> str:
    """Replace the content between BEGIN/END markers (for the given label), or append a new block."""
    begin = f"<!-- BEGIN GENERATED: {label} -->"
    end = f"<!-- END GENERATED: {label} -->"
    block = f"{begin}\n{GENERATED_NOTE}\n\n{generated_body.rstrip()}\n\n{end}"
    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end),
        re.DOTALL,
    )
    if pattern.search(content):
        return pattern.sub(block, content)
    # No markers present — append to end of file
    trimmed = content.rstrip() + "\n\n" + block + "\n"
    return trimmed


def write_or_diff(path: Path, new_content: str, check: bool) -> bool:
    """Return True if the file is (or would be) changed."""
    original = path.read_text(encoding="utf-8") if path.exists() else ""
    if original == new_content:
        return False
    if check:
        diff = difflib.unified_diff(
            original.splitlines(keepends=True),
            new_content.splitlines(keepends=True),
            fromfile=str(path) + " (on disk)",
            tofile=str(path) + " (expected)",
        )
        sys.stderr.writelines(diff)
        return True
    path.write_text(new_content, encoding="utf-8")
    print(f"updated: {path.relative_to(REPO_ROOT)}")
    return True


def process_family(
    family_id: str,
    categories: dict[str, dict[str, list[dict]]],
    taxonomy_index: dict[str, dict],
    check: bool,
) -> bool:
    """Update the family README and each category doc. Returns True on change."""
    changed = False
    family_dir = FAMILIES_DIR / family_id
    if not family_dir.exists():
        sys.stderr.write(f"error: missing family directory {family_dir}\n")
        return True  # treat as drift

    # Resolve family name from any leaf
    family_name = family_id
    sample_cat = next(iter(categories.keys()), None)
    if sample_cat:
        sample_leaf = next(iter(categories[sample_cat].keys()), None)
        if sample_leaf:
            meta = taxonomy_index.get(f"{family_id}.{sample_cat}.{sample_leaf}", {})
            family_name = meta.get("family_name", family_id)

    # Family README
    readme_path = family_dir / "README.md"
    if readme_path.exists():
        body = render_family_catalog(family_id, family_name, categories, taxonomy_index)
        new = splice_generated(readme_path.read_text(encoding="utf-8"), body, CATALOG_LABEL)
        changed |= write_or_diff(readme_path, new, check)

    # Category docs
    for category_id, leaves_by_id in categories.items():
        cat_path = family_dir / f"{category_id}.md"
        if not cat_path.exists():
            sys.stderr.write(f"warning: missing category doc {cat_path}\n")
            continue
        sample_leaf_id = next(iter(leaves_by_id.keys()))
        category_meta = taxonomy_index.get(
            f"{family_id}.{category_id}.{sample_leaf_id}", {}
        )
        body = render_category_catalog(category_meta, leaves_by_id, taxonomy_index)
        new = splice_generated(cat_path.read_text(encoding="utf-8"), body, CATALOG_LABEL)
        changed |= write_or_diff(cat_path, new, check)

    return changed


def _overview_row(attack: dict, category_name: str, leaf_name: str) -> str:
    name = _escape_cell(attack.get("name", ""))
    category = _escape_cell(category_name)
    leaf = _escape_cell(leaf_name)
    paper = _md_link("Link", attack.get("paper_url"))
    repo = _md_link("Repo", attack.get("repo_url"))
    venue = _escape_cell(attack.get("venue", ""))
    year = _escape_cell(attack.get("year", ""))
    return f"| {name} | {category} | {leaf} | {paper} | {repo} | {venue} | {year} |"


def render_attacks_overview(grouped: dict, taxonomy_index: dict[str, dict]) -> str:
    """Render the full cross-family catalog as a single attacks-overview.md body.

    Structure:
      - Summary line + per-family count table
      - One <details> block per family (collapsed by default) containing a
        single table with columns:
          Attack | Category | Leaf | Paper | Repository | Venue | Year
        Rows sorted by category_name, leaf_name, attack_name.
    """
    # Family name lookup and per-family attack counts
    family_names: dict[str, str] = {}
    for meta in taxonomy_index.values():
        family_names.setdefault(meta["family_id"], meta["family_name"])
    per_family_counts: list[tuple[str, str, int]] = []  # (family_id, family_name, count)
    total_attacks = 0
    for family_id in sorted(grouped.keys()):
        cats = grouped[family_id]
        count = sum(len(a) for leaves in cats.values() for a in leaves.values())
        total_attacks += count
        per_family_counts.append((family_id, family_names.get(family_id, family_id), count))

    # Count categories and leaves actually populated
    cat_count = sum(len(cats) for cats in grouped.values())
    leaf_count = sum(
        len(leaves) for cats in grouped.values() for leaves in cats.values()
    )

    out: list[str] = []
    out.append("## Summary")
    out.append("")
    out.append(
        f"*{total_attacks} documented attacks across "
        f"{len(grouped)} families, {cat_count} categories, and {leaf_count} leaves.*"
    )
    out.append("")
    out.append("| Family | Attacks |")
    out.append("|--------|--------:|")
    for family_id, family_name, count in sorted(per_family_counts, key=lambda x: x[1].lower()):
        family_link = f"families/{family_id}/README.md"
        out.append(f"| [{family_name}]({family_link}) | {count} |")
    out.append("")
    out.append("## Attacks by Family")
    out.append("")
    out.append(
        "_Each family is collapsed by default. Click a family to expand its table._"
    )
    out.append("")

    for family_id, family_name, count in sorted(per_family_counts, key=lambda x: x[1].lower()):
        cats = grouped[family_id]
        out.append("<details>")
        out.append(f"<summary><b>{family_name}</b> &mdash; {count} attacks</summary>")
        out.append("")
        out.append("| Attack | Category | Leaf | Paper | Repository | Venue | Year |")
        out.append("|--------|----------|------|-------|------------|-------|------|")

        # Flatten all attacks in this family into (category_name, leaf_name, attack) tuples
        rows: list[tuple[str, str, str, str]] = []  # (cat_name, leaf_name, attack_name_lc, rendered_row)
        for category_id, leaves_by_id in cats.items():
            for leaf_id, attacks in leaves_by_id.items():
                meta = taxonomy_index.get(
                    f"{family_id}.{category_id}.{leaf_id}", {}
                )
                category_name = meta.get("category_name", category_id)
                leaf_name = meta.get("leaf_name", leaf_id)
                for attack in attacks:
                    rows.append((
                        category_name,
                        leaf_name,
                        attack.get("name", "").lower(),
                        _overview_row(attack, category_name, leaf_name),
                    ))
        for _, _, _, row in sorted(rows, key=lambda r: (r[0].lower(), r[1].lower(), r[2])):
            out.append(row)
        out.append("")
        out.append("</details>")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def process_overview(
    grouped: dict,
    taxonomy_index: dict[str, dict],
    check: bool,
) -> bool:
    """Update taxonomy/attacks-overview.md. Returns True on change."""
    if not OVERVIEW_FILE.exists():
        sys.stderr.write(
            f"error: missing overview file {OVERVIEW_FILE}. "
            f"Create it with a title, intro paragraph, and BEGIN/END "
            f"GENERATED: {OVERVIEW_LABEL} markers.\n"
        )
        return True  # treat as drift
    body = render_attacks_overview(grouped, taxonomy_index)
    new = splice_generated(OVERVIEW_FILE.read_text(encoding="utf-8"), body, OVERVIEW_LABEL)
    return write_or_diff(OVERVIEW_FILE, new, check)


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if any file would change. Used in CI.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    attacks_doc = load_yaml(ATTACKS_FILE)
    taxonomy_doc = load_yaml(TAXONOMY_FILE)
    index = build_taxonomy_index(taxonomy_doc)
    attacks = attacks_doc.get("attacks", [])
    grouped = group_attacks(attacks, index)

    changed_any = False
    for family_id, categories in sorted(grouped.items()):
        changed_any |= process_family(family_id, categories, index, args.check)

    # Cross-family overview (single attacks-overview.md)
    changed_any |= process_overview(grouped, index, args.check)

    if args.check and changed_any:
        sys.stderr.write(
            "\nerror: attack tables are out of sync with taxonomy/attacks.yaml.\n"
            "Run: python scripts/generate_tables.py\n"
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
